PHPC-1792: Changed all copyrights to be <year>-Present
mongodb/mongo-php-driver pull request #1217
Opened 2021-04-16 21:39 UTC by agolin95

Some of these were in the form of `Copyright <year> MongoDB, Inc.` as opposed to `Copyright <year>=<year> MongoDB, Inc.` - I changed those as well assuming we would want equivalence across files, but please lmk if that was an incorrect assumption!

2021-04-16 23:45 UTC, jmikola commented
I'm in favor of lowercase "present". That was in the original template from legal and I believe it is what is used in other projects (server for sure).

As for changing `<year>` to `<year>-present`, I think that's correct. Before we started using "present", files that were introduced only received the current year. If they were updated in a later year, that line was then updated with a range. So all copyright lines in the driver should now be in the form "<first year introduced>-present". 

> template updated accordingly

FYI, `template.rc` is just a file for the Windows DLL produced by PECL. It's serves no purpose for the driver itself.

2021-04-29 03:16 UTC, agolin95 commented
@jmikola thank you for the review and sorry for the delay! Pushed a commit that changes titlecase "Present" to lowercase "present"

2021-04-29 06:24 UTC, alcaeus approved these changes
LGTM besides the template.rc change

2021-04-29 06:24 UTC, alcaeus commented on template.rc
> +            VALUE "LegalCopyright", "Copyright � 2014-present MongoDB, Inc."
This looks jumbled, I think we can revert the change to this file.

2021-04-29 14:08 UTC, alcaeus requested changes

2021-04-29 14:08 UTC, alcaeus commented on template.rc
> +            VALUE "LegalCopyright", "Copyright � 2014-present MongoDB, Inc."
```suggestion
            VALUE "LegalCopyright", "Copyright © 2014-present MongoDB, Inc."
```

2021-04-30 13:12 UTC, alcaeus approved these changes

2021-05-03 13:04 UTC, merged