PHPC-2398: Use server_id methods for libmongoc 1.28+
mongodb/mongo-php-driver pull request #1582
Opened 2024-06-12 13:27 UTC by jmikola

https://jira.mongodb.org/browse/PHPC-2398

Bumps libmongoc to 1.28-dev

2024-06-12 13:58 UTC, alcaeus requested changes
Evergreen config needs regenerating.

Note: I don't think we need to update the SBOM for this change, especially considering that I forgot how nasty the development version info is. It would need some parsing and/or different handling in order to produce a proper purl.

2024-06-12 13:58 UTC, alcaeus commented on .evergreen/config/templates/build/build-libmongoc.yml
> +          LIBMONGOC_VERSION: "master"
This necessitates regenerating the actual build configs.

2024-06-12 14:51 UTC, jmikola commented
> Note: I don't think we need to update the SBOM for this change, especially considering that I forgot how nasty the development version info is. It would need some parsing and/or different handling in order to produce a proper purl.

Agreed. I skipped that step from [CONTRIBUTING.md](https://github.com/mongodb/mongo-php-driver/blob/master/CONTRIBUTING.md#updating-bundled-libraries) and think it makes sense to do so provided we never cut a stable release on a dev version of libmongoc.

2024-06-12 17:05 UTC, jmikola commented
Evergreen test failures are related to [PHPC-2401](https://jira.mongodb.org/browse/PHPC-2401), since [CDRIVER-4828](https://jira.mongodb.org/browse/CDRIVER-4828) has already been completed in libmongoc 1.28-dev. I'll look into this while this PR is open so we can avoid build failures after merging.

2024-06-13 10:25 UTC, alcaeus approved these changes

2024-06-14 13:46 UTC, merged